### ISSUE TITLE
Testing...

### ISSUE THREAD

**Issue by MSG100TC** [MSG100TC/Respository-1#1]
Testing

**Comment by SOF3** [comment]
Hi @MSG100TC, I don't know how to contact you, so I just comment here.
I would like to remind you that the "Accept"/"Reject" button on Poggit is to determine whether the plugin should be released, not to determine whether you _like_ the plugin. Even a plugin has bad config etc., as long as it is functional, it should be acceptable on Poggit. The "Reject" button should only for plugins that you think it's not reasonable to be released at all.

**Comment by SOF3** [comment]
Of course, "not easy to config" is still a valid reason if it is too specific and not customizable at all.

**Comment by MSG100TC** [comment]
Oh, Alright. I thought the Reject button is determined whether you like the plugin or not, now I understand. Thanks for reminding me that.

Sorry for the inconvenience.
